import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedAlgebraicErrorCodeMessageMap: ErrorCodeMessageMap = {
	DivisionByZero: { ja: "Division by zero", en: "Division by zero" },
	InvalidNumber: { ja: "Invalid number format", en: "Invalid number format" },
	ParseError: { ja: "Parse error", en: "Parse error" },
	RationalOverflow: { ja: "Rational number overflow", en: "Rational number overflow" },
	UnexpectedCharacter: { ja: "Unexpected character", en: "Unexpected character" },
	UnexpectedEof: { ja: "Unexpected end of input", en: "Unexpected end of input" },
	UnexpectedToken: { ja: "Unexpected token", en: "Unexpected token" },
	UnknownFunction: { ja: "Unknown function or variable", en: "Unknown function or variable" },
};
