import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedLinalgErrorCodeMessageMap: ErrorCodeMessageMap = {
	DimensionMismatch: { ja: "DimensionMismatch", en: "DimensionMismatch" },
	ExactSizeLimit: { ja: "ExactSizeLimit", en: "ExactSizeLimit" },
	IndexOutOfBounds: { ja: "IndexOutOfBounds", en: "IndexOutOfBounds" },
	InvalidArgument: { ja: "InvalidArgument", en: "InvalidArgument" },
	InvalidDimension: { ja: "InvalidDimension", en: "InvalidDimension" },
	NotImplemented: { ja: "NotImplemented", en: "NotImplemented" },
	NotSquareMatrix: { ja: "NotSquareMatrix", en: "NotSquareMatrix" },
	SingularMatrix: { ja: "SingularMatrix", en: "SingularMatrix" },
};
