// --- Auto-generated Dispatcher ---
// Do not edit this file manually.

pub mod runner_algebraic;
pub mod runner_coding;
pub mod runner_common;
pub mod runner_concrete_math;
pub mod runner_finite_field;
pub mod runner_linalg;
pub mod runner_polynomial;
pub mod runner_signal_processing;
pub mod runner_source_coding;
pub mod runner_statistics;

pub fn dispatch_test(crate_name: &str, func_key: &str, inputs: &[String]) -> std::result::Result<String, String> {
    match crate_name {
        "algebraic" => runner_algebraic::run_dynamic_test(func_key, inputs),
        "coding" => runner_coding::run_dynamic_test(func_key, inputs),
        "common" => runner_common::run_dynamic_test(func_key, inputs),
        "concrete-math" => runner_concrete_math::run_dynamic_test(func_key, inputs),
        "finite-field" => runner_finite_field::run_dynamic_test(func_key, inputs),
        "linalg" => runner_linalg::run_dynamic_test(func_key, inputs),
        "polynomial" => runner_polynomial::run_dynamic_test(func_key, inputs),
        "signal-processing" => runner_signal_processing::run_dynamic_test(func_key, inputs),
        "source-coding" => runner_source_coding::run_dynamic_test(func_key, inputs),
        "statistics" => runner_statistics::run_dynamic_test(func_key, inputs),
        "test-cases" => {
            if let Some((target, func)) = func_key.split_once("::") {
                dispatch_test(target, func, inputs)
            } else {
                Err(format!("Invalid combined function key: {}", func_key))
            }
        },
        _ => Err(format!("Unknown crate: {}", crate_name)),
    }
}
