import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedStatisticsErrorCodeMessageMap: ErrorCodeMessageMap = {
	DomainError: { ja: "Domain error in {what}", en: "Domain error in {what}" },
	EmptyInput: { ja: "Input data is empty", en: "Input data is empty" },
	InvalidParameter: { ja: "Invalid parameter for {what}", en: "Invalid parameter for {what}" },
};
