import type { ErrorCodeMessageMap } from "./appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: commonErrorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedCommonErrorCodeMessageMap: ErrorCodeMessageMap = {
	InternalServerError: { ja: "Internal server error occurred", en: "Internal server error occurred" },
	InvalidInput: { ja: "Invalid input provided", en: "Invalid input provided" },
	NotFound: { ja: "Resource not found", en: "Resource not found" },
};
