import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedSourceCodingErrorCodeMessageMap: ErrorCodeMessageMap = {
	DecodeError: { ja: "decode error", en: "decode error" },
	DecodeMismatch: { ja: "decode mismatch", en: "decode mismatch" },
	ElementDecodeError: { ja: "decode error at element {0}", en: "decode error at element {0}" },
	EmptyInput: { ja: "empty input", en: "empty input" },
	Huffman: { ja: "inner huffman error", en: "inner huffman error" },
	InvalidDistribution: { ja: "invalid probability distribution", en: "invalid probability distribution" },
	InvalidMagic: { ja: "invalid magic", en: "invalid magic" },
	InvalidSymbolCount: { ja: "invalid symbol count", en: "invalid symbol count" },
	LengthMismatch: { ja: "length mismatch", en: "length mismatch" },
	NonAsciiInput: { ja: "non-ascii input", en: "non-ascii input" },
	ProbabilityError: { ja: "probability error", en: "probability error" },
	RangeError: { ja: "range error", en: "range error" },
	Truncated: { ja: "truncated stream", en: "truncated stream" },
	UnsupportedVersion: { ja: "unsupported version", en: "unsupported version" },
};
