import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedFiniteFieldErrorCodeMessageMap: ErrorCodeMessageMap = {
	DegreeOverflow: { ja: "DegreeOverflow", en: "DegreeOverflow" },
	DivisionByZero: { ja: "DivisionByZero", en: "DivisionByZero" },
	InvalidArgument: { ja: "InvalidArgument", en: "InvalidArgument" },
	InvalidModulus: { ja: "InvalidModulus", en: "InvalidModulus" },
	NotImplemented: { ja: "NotImplemented", en: "NotImplemented" },
};
