import type { ErrorCodeMessageMap } from "../../../shared/errors/appError";

// =============================================
// THIS FILE IS AUTO-GENERATED.
// DO NOT EDIT THIS FILE BY HAND.
//
// Edit overrides in: errorCodeMessages.ts
// Regenerate via: cargo run -p inspector -- error-messages
// =============================================

// Auto-generated by inspector (error-messages).
// Source: Rust error enums (thiserror + AsRefStr).
// - Keys are error `code` values.
// - Values are generic messages (no dynamic placeholders).

export const generatedCodingErrorCodeMessageMap: ErrorCodeMessageMap = {
	DecodeFailure: { ja: "DecodeFailure", en: "DecodeFailure" },
	InvalidArgument: { ja: "InvalidArgument", en: "InvalidArgument" },
	InvalidParameters: { ja: "InvalidParameters", en: "InvalidParameters" },
	NotImplemented: { ja: "NotImplemented", en: "NotImplemented" },
	RankDeficient: { ja: "RankDeficient", en: "RankDeficient" },
};
